import Image from 'next/image'
import './globals.css'
import { Inter } from 'next/font/google'
import { AiFillYoutube } from 'react-icons/ai';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={[inter.className]}>
        <header className="py-2 shadow-md shadow-gray-600">
          <nav className="flex container mx-auto justify-between items-center">
            <AiFillYoutube className="text-red-500 w-20 h-20" />
            <div className="flex items-center flex-grow justify-center"> {/* Centered container */}
              <input type="text" placeholder="Search movie" className="w-1/2 px-4 py-2 rounded-lg" />
            </div>
          </nav>
        </header>
        
        {children}
      </body>
    </html>
  )
}
